name: atomic_design_tool
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.1.246

  # Atomic Design package
  atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/mobile-layers.git
      path: packages/atomic_design
      ref: enhancement/style

  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  gap: ^3.0.1

dependency_overrides:
  atomic_design:
    path: /Users/mohamed/StudioProjects/alkhbaz-platform/mobile-layers/packages/atomic_design

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
