name: atomic_design_tool
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.1.246

  # Atomic Design package
  tot_atomic_design:
    path: /Users/mohamed/StudioProjects/ui_component/tot_atomic_design
  atomic_design:
    path: /Users/mohamed/StudioProjects/alkhbaz-platform/mobile-layers/packages/atomic_design
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
